# Generated by Django 5.2.3 on 2025-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system_stock',
            field=models.IntegerField(default=0),
        ),
    ]
