# Generated by Django 5.2.3 on 2025-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_system_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='damaged_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
