# Generated by Django 5.2.3 on 2025-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockentry_damaged_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
